### ISSUE TITLE
Feature Request: Add an option to update files

### ISSUE THREAD

**Issue by vKnmnn** [aguslr/multibootusb#116]
When there have been a few fixes, like today, it would be much easier to issue
`git pull & makeUSB.sh -u` 
to update the grub config files which have been changed instead of copying them over manually.

**Comment by aguslr** [comment]
The script `makeUSB.sh` is only used to facilitate the creation of a new USB drive.

Pulling files from the repository and copying them into the drive is easily done with a simple `cp` or `rsync` command such as:

    git pull && rsync -vur --delete mbusb.* <mountpoint>/boot/grub/

You could even just clone the repository into your `<mountpoint>/boot/grub/` and do a `git pull` when needed.

However, for the script to be able to do all this, we'd need to detect the mountpoint and the GRUB directory (`/boot/grub` or `/boot/grub2`). Besides, the script is run as root, so that would mess up with your repository files.

Either way, I don't think this is worth it at all. The script is quite messy already without unnecessary stuff.
