### ISSUE TITLE
Support for Manjaro KDE and Solus-Project

### ISSUE THREAD

**Issue by longtomjr** [aguslr/multibootusb#31]
I have been looking into doing this, and got to the manjaro plymouth screen but not further. I have no clue what to do with the Solus-Project. (the bootoptions mostly)

I am booted back into my windows partition, but can fiddle more on my Fedora part. tomorrow. 

If you have any pointers you can give me on how you did the others it will be much appreciated. :)

**Comment by P0ly** [comment]
Hi, I got Manjaro KDE 16.10.3 working.
It seems the bootoption "misolabel" needs to be adjust to the version number.
But probably needs further testing...

What I **changed** for example:
menuentry "start (x86_64)" {
      bootoptions="img_dev=$imgdevpath img_loop=$isofile64 earlymodules=loop misobasedir=manjaro misolabel=MJRO**1610** nouveau.modeset=1 i915.modeset=1 radeon.modeset=1 logo.nologo overlay=free quiet splash showopts"
      linux (loop64)/manjaro/boot/x86_64/manjaro $bootoptions
      initrd (loop64)/manjaro/boot/x86_64/manjaro.img
}

My grub.d/manjaro.d/16.10.3-kde.cfg: [16.10.3-kde.txt](https://github.com/aguslr/multibootusb/files/691413/16.10.3-kde.txt)

**Comment by P0ly** [comment]
I only tested x86_64 arch

**Comment by aguslr** [comment]
Thanks @P0ly for sorting that out. I'll have a look at the ISO file for Solus and see if we can make it work.

**Comment by baconicsynergy** [comment]
I definitely agree about adding Solus (budgie/mate) and alternative Manjaro flavors

**Comment by aguslr** [comment]
Hey, @baconicsynergy!

All Manjaro flavors (even Community Editions) should work with the current configuration since only the desktop environment changes.

I just tested several flavors for Manjaro 17.0.2 and they all work except the KDE ISO which, to be fair, doesn't boot either when run by its own.

Regarding Solus, it seems it's not possible to make it work at the moment. I have created a new issue (#99) specific for Solus, therefore I will close this one.
