### ISSUE TITLE
[feature request] support debian test build

### ISSUE THREAD

**Issue by alex-tu-cc** [aguslr/multibootusb#40]
[feature request] support debian test build ex, weekly build or daily build

**Comment by alex-tu-cc** [comment]
a pull request is for this feature.
https://github.com/aguslr/multibootusb/pull/39

**Comment by aguslr** [comment]
Hi alex-tu-cc,

How would this work? It seems a little bit more complicated than the usual ISO file loaded into loopback.

**Comment by alex-tu-cc** [comment]
introduced this patch is because of debian testing images detecting cd-rom during installing, so that users could not just use the exists configurations to loopback ISO files for installing Debian testing images.

Then refer to [1] and [2], there is a loader could do that to let user select what ISO they would like to load in GUI menu. And I verified it with debian-testing-amd64-netinst.iso, it works perfectly.

[1] https://www.debian.org/releases/stable/amd64/ch05s01.html.en
[2] https://lists.debian.org/debian-user/2012/12/msg00194.html

**Comment by aguslr** [comment]
Thanks for the information, @alex-tu-cc!

I've tried it and it seems overly complicated way to support booting Debian testing. This goes beyond using a single ISO or kernel file to boot, since it requires 3 files.

For this situation, I would suggest using [Debian Network boot](https://www.debian.org/distrib/netinst) or some iPXE disk like [netboot.xyz](https://netboot.xyz/) with which many distros can be installed from the network.
