### ISSUE TITLE
more generic configs

### ISSUE THREAD

**Issue by P0ly** [aguslr/multibootusb#41]
I think it would be a great Idea to create fallback configs,
which loop trough the isos-folder and create boot entries for them.
This will be probably a better solution, instead just changing the names
of the isos the config files all the time.

**Comment by P0ly** [comment]
As example with Arch Linux #42

**Comment by aguslr** [comment]
That's a great solution for distros like Arch Linux that are frequently updated (weekly/monthly) without changing the boot options. Although, I don't quite like the fact that the whole path to the ISO appears in `$isofile`, which clutters the menu entry a bit but I don't think it can be helped.

Either way, this might work great for distros like SystemRescueCD or GParted too. Other distros, like Fedora or Manjaro, which require small changes (CDLABEL, misolabel, etc.), could be improved by sourcing a config file (`params.inc` maybe?) with the redundant parameters.

We should look into other distros/configs that would benefit from this.

**Comment by P0ly** [comment]
Yeah, about the long names... didn't know how to filter the string of` $isofile`(it's basically "bash-scripting" but I am not an expert :/). Also `submenu` does not work well with variables that were defined out of it, the variables just doesn't exist anymore in them.
But yeah the basic idea just was to have a "general" config file for every distro, that loads(hopefully) the iso if no configs for it are defined. As a "fallback".

**Comment by aguslr** [comment]
Unfortunately, [Grub scripts](https://www.gnu.org/software/grub/manual/html_node/Shell_002dlike-scripting.html) are only similar to bash but not as powerful.

However, after messing around for a while in Grub's command line, I noticed that this works:

`eval regexp --set=isoname "$isopath/\(.*\)" $isofile`

This removes the path from `$isofile` and saves it to a new variable `$isoname`. This could be set inside the for-loop for each `$isofile` and use it in a submenu entry like so:

```
# fallback
if [ -e $isopath/archlinux-* ]; then
  submenu "[Fallback] ->" {
    for isofile in $isopath/archlinux-*; do
      eval regexp --set=isoname "$isopath/\(.*\)" $isofile
      loopback loop $isofile
      submenu "[$isoname] ->" {
        menuentry "Arch Linux (i686)" {
          bootoptions="img_dev=$imgdevpath img_loop=$isofile earlymodules=loop"
          linux (loop)/arch/boot/i686/vmlinuz $bootoptions
          initrd (loop)/arch/boot/i686/archiso.img
        }
        if cpuid -l ; then # Check whether CPU is 64-bit
          menuentry "Arch Linux (x86_64)" {
            bootoptions="img_dev=$imgdevpath img_loop=$isofile earlymodules=loop"
            linux (loop)/arch/boot/x86_64/vmlinuz $bootoptions
            initrd (loop)/arch/boot/x86_64/archiso.img
          }
        fi
      }
    done
  }
fi
```

I think this is much cleaner and streamlined. We could actually go ahead and remove the old config files for Arch and also remove the `[Fallback]` submenu since all Arch ISO files use these options.

**Comment by aguslr** [comment]
Ok, after some testing, I found that there seem to be several problems with this approach.

First of all, as you mentioned, `submenu` doesn't work well with variables set out of it. This can be easily fixed by adding `export isofile` inside the for-loop.

However, the variable `$isofile` is set in every iteration of the for-loop but is not expanded until the menuentry is booted. This means that, no matter what, `$isofile` (and probably `(loop)` too) will always be set to the last ISO file found. With one ISO file there is no problem, but with more than one, it'll always boot the last one.

A possible *solution* (more like a hack) would be to only run the for-loop once by adding a `break` at the end. This would help those that just replace an old ISO file with the newest version but wouldn't work for those that want to keep several versions of the same distro (f.e. Ubuntu 16.04 LTS and 16.10).

**Comment by P0ly** [comment]
Hi @aguslr ,
The `$isoname` variable works great. Didn't notice this issue with `$isofile` at first, really don't know ho to fix this.
Let us use your hack with `break`  to at least have one boot entry without the user needs to mess around with config files, if the configs are outdated.

**Comment by aguslr** [comment]
In the end I went with [a common file with generic entries being source by the config files](https://github.com/aguslr/multibootusb/tree/f512a0658a2c15f0232b981f2b37f20241c3f1e7/grub.d/arch.d). What do you think?

The problem with using `break` is that, since the for-loop loads the ISO files alphabetically, only the oldest ISO file is displayed, instead of the latest.

**Comment by aguslr** [comment]
@Poly, I finally got it working thanks to [this entry in Grub's mailing list](https://lists.gnu.org/archive/html/help-grub/2016-01/msg00065.html). Yay!

Check it out in commit 8b10af0. I went ahead and removed the other config files for Arch because they are no longer needed.

Now to see what other distros can benefit from this approach.

**Comment by P0ly** [comment]
Nice work @aguslr,
this will definitely improve this project!
Looking forward to implement this for more distros too.

**Comment by aguslr** [comment]
@P0ly,

I've finally migrated [most config files to a generic style file](https://github.com/aguslr/multibootusb/tree/bd54d6d82ecac4bcda7869859feb89541e3d88b2/).

**Comment by P0ly** [comment]
Good job @aguslr!
Only Tiny Core remains, I think. I will do this some time. 
Also working on adding Alpine Linux.

**Comment by aguslr** [comment]
Well, regarding TinyCore, see commit 31cc8f1. It's 3 files but, since each version has such different menu entries, it seems to be the best option.

**Comment by P0ly** [comment]
Oh OK, well done. You are faster then me :)
I found out that I forgot something in the initial commit of Tiny Core: 
I guess, I can close this now.
