### ISSUE TITLE
Slow grub rendering

### ISSUE THREAD

**Issue by pedro-nonfree** [aguslr/multibootusb#55]
Great piece of software. I was looking something like this.

Each grub menu delays like 1.5 seconds in the render, and I have to traverse 3 screens.
The screen I'm using is quite big, probably 19xx x 1080 or something like this.

I hope there is a grub option to use a very low resolution as 800x600

Any idea? Help

**Comment by aguslr** [comment]
Hi @pedro-nonfree! Glad you like the project. :smiley:

To use a low resolution, you have a few options:

1. During boot, if you press and hold `SHIFT`, it will skip the graphical menu and use the basic console.
2. In 6a7f2e16, I've added an option to load a custom configuration file (`grub.cfg.local`), where you could force the use of the console, by adding the following:

        terminal_output console
        terminal_input console

Check [GRUB's manual](https://www.gnu.org/software/grub/manual/html_node/terminal_005finput.html) for more information about these two commands.

Also, the more ISO files you have, the slower the menu will be since it scans the pendrive and loads the appropriate configuration for each ISO. Obviously, the speed of the drive has some impact too.

**Comment by vKnmnn** [comment]
i had this issue too, i used mbusb.cfg.local to set the following:
```
set gfxmode=960x540,1024x576,1280x720,1600x900,1920x1080,auto
set gfxpayload=keep,auto
```
and all menues render quickly now.

**Comment by aguslr** [comment]
@vKnmnn, good point. You can indeed set a list of resolutions with [gfxmode](https://www.gnu.org/software/grub/manual/grub/html_node/gfxmode.html).

**Comment by pedro-nonfree** [comment]
I did not tested but @aguslr what do you think to put @vKnmnn suggested options as default. Seems it is good in general.

**Comment by aguslr** [comment]
@pedro-nonfree, I don't think that forcing smaller resolutions by default is the solution here. Especially since the provided `grub.cfg.example` is just a sample to be used if you don't have a custom `grub.cfg`.

You can customize `grub.cfg` as you please or use `mbusb.cfg.local` instead and they won't be overwritten. Adding to `mbusb.cfg.local` these lines should do the trick:

```
terminal_output console
terminal console
```

Or something like what @vKnmnn suggested.
