### ISSUE TITLE
No Boot with Hiren's

### ISSUE THREAD

**Issue by vKnmnn** [aguslr/multibootusb#57]
i noticed, that in the hirens.d the name of the iso is misspelled. the iso from the website is `Hiren's.BootCD.15.2.iso` whereas the script looks for `Hirens.BootCD*`
changing the name of the file seems to work so far as it shows the next menu properly, but none of the item's actually boot.
cheers

**Comment by aguslr** [comment]
Hi @LordTaifleh,

Yes, renaming the ISO is neccessary in order to remove the apostrophe. Check the [notes for this distro](http://mbusb.aguslr.com/distros/hirens.html#notes) for more information as to why.

Regarding your second issue, is this an EFI system? If so, this is probably related to issue #56, which can be solved by [enabling CSM](https://en.wikipedia.org/wiki/Unified_Extensible_Firmware_Interface#CSM_booting).

If not, could you please provide some more information about your setup and what options you used when creating the USB?

**Comment by LordTaifleh** [comment]
on the first problem, sorry, should have read the info-page for the boot disc.
regarding the second problem:
Yes, it's an EFI system. enabling CSM does not change the behaviour. The screen goes blank and the computer seems frozen, not reacting to any keypress and not recovering from this state.
I created the USB with the script included in this repo, using the options `-e -b` 
interestingly it doesn't boot in bios mode at all on this computer, while it did on some other computer in bios mode (or combined mode, if i recall correctly). i'll test more on this when i'm home.

**Comment by aguslr** [comment]
Thanks for the info, @LordTaifleh. I believe the problem may be that HIren's CD [doesn't support UEFI](https://superuser.com/a/952362) although that should still work with CSM.

I have tried booting the ISO directly in a UEFI virtual machine and it's not even detected. If CSM is enabled, it does show the boot menu but most options fail with low memory issues even though the VM has 2G.

I cannot know if this is a problem with the virtualization or with the CD itself, since I cannot test the CD on a UEFI physical machine at the moment.

**Comment by ZehL** [comment]
I also have this problem. If I boot on an old BIOS machine it boots just fine and can use all options. But on a UEFI machine even with CSM enabled it gives me an error. As soon as I enter the selection it says: "Error couldn't find suitable memory target" and then it goes into memdisk with the error "MEMDISK: No ramdisk image specified!" I have tried on a lot of diferent machines from Desktops to Laptops since I work at a Tech center. It would really be useful to have HBCD working on my multiboot but as it is I can only use it on BIOS machines. I believe some of the other memdisk isos also give this error on some UEFI machines with CSM enabled. Isn't there a way to chainload grub2 into grub4dos with HBCD since it uses grub4dos?

**Comment by ob7** [comment]
Hirens will boot for me but on some systems starts outputting USB errors over and over again even if I burn Hirens straight to a CD ( so its probably not an issue with multiboot )

**Comment by ZehL** [comment]
Well for me it must be multiboot. Because I have a USB just with hirens that I created according to hirens website and it's that USB that I have to use on the PC that multiboot gives me the couldn't find suitable memory target.

**Comment by aguslr** [comment]
@ZehL, does this USB work on EFI machines with or without CSM?

It's true that MEMDISK cannot be used on EFI systems but you should see a submenu `Hirens.BootCD.15.2.iso (custom)` that does not use MEMDISK at all although a few options are missing, namely `Mini Windows XP` and `Dos programs`.

**Comment by ZehL** [comment]
It works perfectly on EFI machines as long as it's a EFI compatible ISO. As for the custom options they also don't work they say invalid magic number. Wierd thing is that on the EFI PC I created the USB it can boot fine with CSM. Just the custom options give the invalid magic number error but that is the only EFI PC I can boot hirens. Also most of the other memdisk utilities...
