### ISSUE TITLE
SLAX persistent mode won't work

### ISSUE THREAD

**Issue by dagmoller** [aguslr/multibootusb#61]
Slax does not save persistent mode...

**Comment by aguslr** [comment]
Hi @dagmoller,

Indeed, it seems it doesn't work. Since we are booting from an ISO, it behaves like a CD and is unable to save the changes.

I found [these manual about boot parameters in SLAX](http://old.slax.org/documentation_boot_cheatcodes.php), but they don't seem to work with newer versions (or at least I was unable to use `changes=` to specify a path for the persistent changes to be saved to).

Therefore, in 5c3f0bf, I've removed these menu entries to avoid confusion.

**Comment by dagmoller** [comment]
Hi @aguslr,

Found a solution...
Just extract isofile to something like /boot/isos/slax-Brazilian-Portuguese-7.0.8-x86_64
Full path is /boot/isos/slax-Brazilian-Portuguese-7.0.8-x86_64/slax

added some lines in $prefix/slax.d/generic*.cfg
```
+  if [ -e $isopath/slax-*-x86_64 ]; then
+    for isofile in $isopath/slax-*-x86_64; do
+      regexp --set=isoname "$isopath/(.*)" "$isofile"
+      submenu "[persist] $isoname ->" "$isofile" {
+        iso_path="$2"
+        source $prefix/grub.d/slax.d/generic-persist.inc
+      }
+    done
+  fi
```

Create $prefix/slax.d/generic-persist.inc

```
+menuentry "Run Slax - Persist Changes" {
+  bootoptions="from=$iso_path/slax vga=normal load_ramdisk=1 prompt_ramdisk=0 rw printk.time=0 slax.flags=perch"
+  linux $iso_path/slax/boot/vmlinuz $bootoptions
+  initrd $iso_path/slax/boot/initrfs.img
+}
```

**Comment by aguslr** [comment]
@dagmoller, that is great!

However, extracting the contents of an ISO kind of defeats the purpose of this project, that is, booting directly from ISO files. Until we find a working solution without this step, I think it's better to remove the entries for persistent mode.

Either way, you can add these custom-made entries in the file `grub.cfg.local` that is loaded by `grub.cfg` automatically so you can still have a working Slax with persistent mode.
