### ISSUE TITLE
tails-amd64-3.0 tor browser

### ISSUE THREAD

**Issue by mbalance** [aguslr/multibootusb#73]
Hi, tails boots fine but the tor browser wont work. I tried on two PCs same issue and I don't really see where the issue could be.

**Comment by aguslr** [comment]
Hello, @mbalance! It seems some of the boot parameters were changed in Tails 3.0. I changed the configuration in commit cbe4bae and it seems to work fine now.

**Comment by mbalance** [comment]
Great. Do I have to run the full script and wipe my USB to apply this update?

Thanks!

**Comment by aguslr** [comment]
Not really, you just need to copy the subdirectory `grub.d` into the directory `boot/grub` on your USB drive. For instance, by running:

```
cp -rf grub.* <usb_mountpoint>/boot/grub/
```

**Comment by mbalance** [comment]
I did that and it showed me duplicate of the tails iso when booting. So I deleted the old tails.d from the stick but now it's showing me a syntax error "Trash". something.

**Comment by aguslr** [comment]
I don't know about that "Trash" thing. Your file manager may have created a `.Trash` directory in the USB drive to move the old `grub.d` directory when you deleted it though.

But yes, you'd have to delete the `grub.d` from the USB drive before copying the new version since some files may have been deleted or renamed. That's why I use [Rsync](https://en.wikipedia.org/wiki/Rsync) instead of just `cp`:

```
rsync -Pr --delete grub.* <usb_mountpoint>/boot/grub/
```

This way I can be sure that the `grub` directory in the USB drive matches the one in the repository.
