### ISSUE TITLE
Support for Debian GNU/kFreeBSD

### ISSUE THREAD

**Issue by baconicsynergy** [aguslr/multibootusb#83]

**Comment by aguslr** [comment]
Hey @baconicsynergy!

Debian GNU/kFreeBSD works with the current configuration files for [Netboot ISOs](http://mbusb.aguslr.com/linux/debian.html).

You can download the `mini.iso` (e.g. [current daily image](https://d-i.debian.org/daily-images/kfreebsd-amd64/daily/netboot-10/)) and rename it appropriately (i.e. `debian-daily-kfreebsd-amd64-mini.iso`).

Commit 0f27724 should improve support too since it no longer uses MEMDISK, therefore it can be booted on [UEFI machines](http://www.syslinux.org/archives/2012-September/018468.html).
