### ISSUE TITLE
Add support for CentOS Everything and Minimal

### ISSUE THREAD

**Issue by baconicsynergy** [aguslr/multibootusb#93]

**Comment by victor3dptz** [comment]
CentOS-6.9-i386-bin-DVD1.iso boots up, but when I choose Install System after selecting the language the installer can't find install cd, it appears the anaconda doesn't recognize the mounted iso (or iso isn't mounted in fact). Please fix

**Comment by aguslr** [comment]
@victor3dptz, you're right! It seems that CentOS 6.9 ISO files don't work since they keep trying to find the local media. Something similar happens with Ubuntu and Debian installation ISOs.

Unfortunately, this cannot be fixed since CentOS 6.9 doesn't seem to have support for this, even though [Fedora](https://fedoraproject.org/wiki/QA:Testcase_install_repository_Hard_drive_variation), [Red Hat](https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/Installation_Guide/chap-anaconda-boot-options.html) and, of course, CentOS 7 do. :frowning_face: 

I have added a note in 876f06e so this is clear.
