### ISSUE TITLE
running the script ./makeUSB.sh brings up grub with minimal cli only

### ISSUE THREAD

**Issue by kocjs** [aguslr/multibootusb#98]
However if I add the MSUSB configuration and files to my existing drive, made with the instructions form Arch wiki everything works fine.

May i suggest an small improvement to the excellent work. While trying to get debian 9 live to run using your files, I figured out that "for isofile in $isopath/debian*.iso;" do will boot the install DVD to. I did not make an install form it. The same should work with ubuntu too.

There is a nice example of what is possible.
https://lists.gnu.org/archive/html/help-grub/2016-01/msg00065.html 

This is the first time i report a bug, if you need more information let me know, i will check here.

**Comment by P0ly** [comment]
Hi @kocjs,
first of all welcome to github!
I guess you followed this guide: [https://wiki.archlinux.org/index.php/Multiboot_USB_drive](https://wiki.archlinux.org/index.php/Multiboot_USB_drive)
(Also I didn't know they referenced this repository, interesting)
If you run this script it does all the formatting for you, so you probably do not need this guide at all. The script completely wipes your USB-Drive! So you need to copy the ISO afterwards on the drive, in the `boot/isos` directory.
For details: [http://mbusb.aguslr.com/install.html](http://mbusb.aguslr.com/install.html)
And to make this clear, after you boot you only see a `grub>` cli?

**Comment by P0ly** [comment]
@kocjs you can also mention a related issue with #62.

**Comment by aguslr** [comment]
Hello @kocjs!

As @P0ly mentions, you can [create the pendrive with the script](http://mbusb.aguslr.com/install.html#using-the-script). If you did use the script, what options did you use? What system are you using to boot the pendrive? Is it [UEFI](https://en.wikipedia.org/wiki/UEFI) or [BIOS](https://en.wikipedia.org/wiki/BIOS)?

Regarding your second point, that is possible with some other distros (e.g. [Linux Mint](http://mbusb.aguslr.com/linux/linuxmint.html)) but not with Debian. Specifically, the install DVD won't work because it cannot detect the CD-ROM during the installation process. Same thing with Ubuntu.

Also, the LiveCD for Debian 8 (jessie) wouldn't work since it doesn't have a `/boot/grub/grub.cfg` file. Once newer versions of Debian come out and Debian 8 is no longer supported, we could consolidate all LiveCDs into one configuration file that loads `/boot/grub/grub.cfg`.

**Comment by kocjs** [comment]
Ok, let me explain better. I am still a beginner.... 
I use Debian stable

I have tried your script two times, i could never choose any options. 
Yes, after I boot I only see a grub> cli?
I boot in bios mode
I am not sure if i did add an ISO before i booted the usb drive.

I made the multiboot drive with the indications of arch wiki and many other sites the last month. I learned a lot and can now use debian and clonezilla live.

I see, it is there any other known way to install the DVD form ISO and multiboot?

thank you

**Comment by kocjs** [comment]
Well when I tried the scrip i did  ./makeUSB.sh /dev/sdx. There are no options asked! 
Now i understand one needs to ./makeUSB.sh -b -e -l /dev/sdx to add hybrid, efi and so on. That was not clear to me.

**Comment by P0ly** [comment]
@kocjs 
If it is still not working, could you run it again with the log-option(-l) enabled and post the content of the `makeUSB.log` file: 
`./makeUSB.sh -b -e -l /dev/sdx`

> I see, it is there any other known way to install the DVD form ISO and multiboot?

Well, you could just write the ISO file on the usb drive like this:
`dd bs=4M if=debian.iso of=/dev/sdx`
But then you could only have one ISO per usb drive and I am not sure if you want that.

**Comment by kocjs** [comment]
I have tried it again and it works now, thank you.

**Comment by P0ly** [comment]
@kocjs Ok then, can you close this issue?

**Comment by aguslr** [comment]
@kocjs It's not possible at the moment to use the Debian DVD install ISO with our multiboot USB, as @P0ly explained.

However, as a side note, if an internet connection is available, you can use the Netboot ISO (i.e. *[mini.iso](http://ftp.debian.org/debian/dists/stable/main/installer-amd64/current/images/netboot/)*) to install Debian on a computer. This way, instead of getting the packages from the DVD, it will download them directly from Debian's repositories during installation. For it to work, you'll need to rename the ISO file though ([check footnote 1](http://mbusb.aguslr.com/linux/debian.html#fn:note1)).
